export const TICKET_STATUS_ID = {
	EXPIRED: 'TKE',
	ON_SALE: 'TKO',
	PENDING: 'TKP',
	SOLD_OUT: 'TKS',
	TRASHED: 'TKA',
};

export const TICKET_STATUSES = {
	EXPIRED: 'EXPIRED',
	ON_SALE: 'ON_SALE',
	PENDING: 'PENDING',
	SOLD_OUT: 'SOLD_OUT',
	TRASHED: 'TRASHED',
};

export const TICKET_STATUS_IDS = Object.values(TICKET_STATUS_ID);
