import { Datetime, DateStatus } from '@eventespresso/constants';

const dates: Datetime[] = [
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: -1,
		isActive: true,
		sold: 0,
		dbId: 2,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		isUpcoming: false,
		status: DateStatus.active,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: 10,
		isActive: true,
		sold: 5,
		status: DateStatus.active,
		dbId: 3,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		isUpcoming: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: 10,
		isActive: true,
		sold: 6,
		status: DateStatus.active,
		dbId: 4,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		isUpcoming: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: 10,
		isActive: true,
		sold: 7,
		status: DateStatus.active,
		dbId: 5,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		isUpcoming: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: 10,
		isActive: true,
		sold: 8,
		status: DateStatus.active,
		dbId: 6,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		isUpcoming: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: 10,
		isActive: false,
		isUpcoming: true,
		sold: 9,
		status: DateStatus.active,
		dbId: 7,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
	{
		__typename: 'EspressoDatetime',
		id: 'RGF0ZXRpbWU6ODM=',
		cacheId: '',
		capacity: 10,
		isActive: false,
		isUpcoming: true,
		sold: 10,
		status: DateStatus.active,
		dbId: 8,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isTrashed: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
		venue: '',
	},
];

export default dates;
