import { __ } from '@eventespresso/i18n';

export const DATETIMES_DROPPABLE_ID = 'date-entities-droppable';

export const DATETIME_STATUS = {
	ACTIVE: 'ACTIVE',
	CANCELLED: 'CANCELLED',
	EXPIRED: 'EXPIRED',
	INACTIVE: 'INACTIVE',
	POSTPONED: 'POSTPONED',
	SOLD_OUT: 'SOLD_OUT',
	TO_BE_DETERMINED: 'TO_BE_DETERMINED',
	TRASHED: 'TRASHED',
	UPCOMING: 'UPCOMING',
};

export const DATETIME_STATUS_CODES = {
	ACTIVE: 'DTA',
	CANCELLED: 'DTC',
	EXPIRED: 'DTE',
	INACTIVE: 'DTI',
	POSTPONED: 'DTP',
	SOLD_OUT: 'DTB',
	TO_BE_DETERMINED: 'DTB',
	TRASHED: 'DTT',
	UPCOMING: 'DTU',
};

export const DATETIME_STATUS_LABELS = {
	ACTIVE: __('Active'),
	CANCELLED: __('Cancelled'),
	EXPIRED: __('Expired'),
	INACTIVE: __('Inactive'),
	POSTPONED: __('Postponed'),
	SOLD_OUT: __('Sold Out'),
	TO_BE_DETERMINED: __('TBD'),
	TRASHED: __('Trashed'),
	UPCOMING: __('Upcoming'),
};

export const DATETIME_STATUS_PREDICATES = {
	isActive: DATETIME_STATUS_LABELS.ACTIVE,
	isCancelled: DATETIME_STATUS_LABELS.CANCELLED,
	isExpired: DATETIME_STATUS_LABELS.EXPIRED,
	isInactive: DATETIME_STATUS_LABELS.INACTIVE,
	isPostponed: DATETIME_STATUS_LABELS.POSTPONED,
	isSoldOut: DATETIME_STATUS_LABELS.SOLD_OUT,
	isTBD: DATETIME_STATUS_LABELS.TO_BE_DETERMINED,
	isTrashed: DATETIME_STATUS_LABELS.TRASHED,
	isUpcoming: DATETIME_STATUS_LABELS.UPCOMING,
};

export const USER_SELECTABLE_DATETIME_STATUSES = {
	CALENDAR_CONTROLLED: __('Calendar Controlled'),
	CANCELLED: DATETIME_STATUS_LABELS.CANCELLED,
	POSTPONED: DATETIME_STATUS_LABELS.POSTPONED,
	SOLD_OUT: DATETIME_STATUS_LABELS.SOLD_OUT,
	TO_BE_DETERMINED: DATETIME_STATUS_LABELS.TO_BE_DETERMINED,
};
