apache_modules:
    - mod_rewrite

# 4437 is
#   - E_ERROR
#   - E_PARSE
#   - E_CORE_ERROR
#   - E_COMPILE_ERROR
#   - E_USER_ERROR
#   - E_RECOVERABLE_ERROR

core config:
    extra-php: |
        error_reporting(4437);
