name: template
type: wordpress
php_version: '8.1'
webserver_type: nginx-fpm
no_project_mount: true
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: '10.4'
use_dns_when_possible: true
composer_version: '2'
web_environment: []
webimage_extra_packages: [php8.1-uopz]
nodejs_version: '18'
hooks:
    post-start:
        - exec: wp core download
        - exec: wp config create --dbname=db --dbuser=db --dbpass=db --dbhost=db # see config.yml for --extra-php under homeadditions
        - exec: /mnt/ddev_config/commands/web/freeze-time "$FREEZE_TIME"
        - exec: wp core install --url="$DDEV_PRIMARY_URL" --title="$DDEV_PROJECT" --admin_user=admin --admin_email=admin@fake.test --admin_password=password
        - exec: wp plugin activate {WP_PLUGINS}
        - exec: wp rewrite structure "/%postname%/"
        - exec: wp rewrite flush --hard # in case we ever use apache
