name: template
type: wordpress
php_version: '8.1'
webserver_type: nginx-fpm
no_project_mount: true
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: '10.4'
use_dns_when_possible: true
composer_version: '2'
web_environment: []
nodejs_version: '18'
hooks:
    post-start:
        - exec: 'wp core download'
        - exec: 'wp config create --dbname=db --dbuser=db --dbpass=db --dbhost=db'
        - exec: 'wp core install --url="$DDEV_PRIMARY_URL" --title="$DDEV_PROJECT" --admin_user=admin --admin_email=admin@fake.test --admin_password=password'
