#!/bin/bash

## Description: Freeze WordPress time so that it is always the same
## Usage: freeze-time
## Example: ddev freeze-time

file='wp-config.php'

if grep -q ClockMock $file; then
  echo 'Error: you have already fixed time in wp-config.php!'
  exit 1
fi

if [[ -z "$1" ]]; then
  echo 'Error: missing timestamp value (taken as a literal string or number)!'
  echo '  for example, ddev freeze-time 1986-06-05'
  echo '  for more details, see PHP docs on new DateTime() constructor'
  exit 1
fi

if [[ ! -f $file ]]
then
  echo "WordPress config not found in current directory!"
  exit 1
fi

composer require slope-it/clock-mock

# https://stackoverflow.com/a/23930212/4343719
read -r -d '' php << EOM
<?php

require __DIR__ . '/vendor/autoload.php';
use SlopeIt\ClockMock\ClockMock;
ClockMock::freeze(new DateTime('$1'));

EOM

sed -i -e 's/<?php//g' $file

config=$(cat $file)

echo "$php" > $file

echo "$config" >> $file
