name: "Auto PR Labeler"
on:
  pull_request:
    # see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
    types: [opened, closed, reopened, ready_for_review, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: eventespresso/actions/packages/auto-pr-labeler@main
      with:
        owner: 'eventespresso'
        repo: 'barista'
        prNumber: ${{ github.event.pull_request.number }}
        token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
