name: "Auto PR Labeler"
on:
  # see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, closed, reopened, ready_for_review, review_requested, review_request_removed]

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: eventespresso/actions/packages/auto-pr-labeler@main
      with:
        org: ${{ github.event.repository.owner.name }}
        repo: ${{ github.event.repository.name }}
        prNumber: ${{github.event.issue.number}}
        token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
