name: 'Chromatic Deployment'

# Event for the workflow
on:
    push:
        branches:
            - sb/**

# List of jobs
jobs:
    chromatic-deployment:
        # Operating System
        runs-on: ubuntu-latest
        name: Chromatic Deployment
        # Job steps
        steps:
            - name: Checkout the commit
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # 👈 Required to retrieve git history

            # TODO replace this when setup-node action supports LTS alias
            - name: Set up Node
              uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            # Install all dependencies at root
            - name: Install dependencies
              # install deps only if lockfile has changed
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

              # 👇 Adds Chromatic as a step in the workflow
            - name: Deploy to Chromatic
              uses: chromaui/action@v1
              # Chromatic GitHub Action options
              with:
                  token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
                  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
