name: Deploy Leading Edge (master)

on:
    push:
        branches: [master]
env:
    API_TOKEN_GITHUB: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
    GIT_USER_EMAIL: ${{ secrets.GH_ACTIONS_GIT_USER_EMAIL }}
    GIT_USER_NAME: ${{ secrets.GH_ACTIONS_GIT_USER_NAME }}
    FORCE_COLOR: true
    PLAYWRIGHT_BROWSERS_PATH: 0 # See https://playwright.dev/docs/ci/#caching-browsers
jobs:
    deploy-domains-and-packages:
        runs-on: ubuntu-latest
        name: Deploy domains and packages
        steps:
            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v1
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

            - name: Checkout and yarn
              uses: eventespresso/actions/packages/checkout-and-yarn@main

            # Build the core domains along with all the packages
            # because all packages will goto core
            - name: Build core domains and all their packages
              run: yarn build:core

            # Deploy the built assets to core repo's assets/dist
            - name: Deploy to event-espresso-core
              run: source tools/deploy.sh "event-espresso-core"
              env:
                  REMOVE_JS_I18N_FILE: 'no'

            - name: Deploy core to cafe repo
              run: source tools/deploy.sh "cafe" "dev" "plugins/event-espresso-core/assets" "plugins/event-espresso-core/languages"

            # Build REM domain without packages
            # because core will load/register the packages
            - name: Build REM with its packages
              run: yarn build:rem

            # Deploy the built assets to REM assets/dist
            - name: Deploy to REM
              run: source tools/deploy.sh "eea-recurring-events-manager"
              env:
                  REMOVE_JS_I18N_FILE: 'no'

            - name: Deploy REM to cafe repo
              run: source tools/deploy.sh "cafe" "dev" "plugins/eea-recurring-events-manager/assets" "plugins/eea-recurring-events-manager/languages"

            # Build WP User domain without packages
            - name: Build wpUser
              run: yarn build:wpUser

            # Deploy the built assets to WP User assets/dist
            - name: Deploy to WP User
              run: source tools/deploy.sh "eea-wpuser-integration"
              env:
                  REMOVE_JS_I18N_FILE: 'no'

            - name: Deploy WP User to cafe repo
              run: source tools/deploy.sh "cafe" "dev" "plugins/eea-wp-user-integration/assets" "plugins/eea-wp-user-integration/languages"

            # Build EventSmart domain without packages
            - name: Build ES EdtrSlots
              run: yarn build:es:edtrSlots

            # Deploy the built assets to ES tester plugin assets
            - name: Deploy to ES website repo
              run: source tools/deploy.sh "eventsmart.com-website" "dev" "plugins/es-barista-tester/assets"
              env:
                  DEPLOY_I18N: 'no'

            # Build upsellAds domain without packages
            - name: Build Upsell Ads
              run: yarn build:es:upsellEditor

            # Deploy the built assets to Upsell/Notifications plugin assets
            - name: Deploy to Upsell Editor
              run: source tools/deploy.sh "eventsmart.com-website" "dev" "plugins/ee-saas-notification/assets"
              env:
                  DEPLOY_I18N: 'no'
