name: E2E Runner

on:
    pull_request_review:
        types: [submitted]
    issue_comment:
        types: [created]

jobs:
    run-tests:
        name: Run E2E Tests
        runs-on: ubuntu-22.04
        if: |
            github.event.review.state == 'approved' ||
            (
                github.event.issue.pull_request &&
                contains(github.event.comment.body, '/run-e2e')
            )
        timeout-minutes: 60
        steps:
            - id: ssh
              name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v2
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}
            - id: get-branch
              name: Get Branch Ref of the Pull Request
              run: |
                  if [ ! -z "${HEAD_REF}" ]
                  then
                    echo "Found branch name in github.event.pull_request.head.ref"
                    echo branch="$HEAD_REF" >> $GITHUB_OUTPUT
                  else
                    echo "Using gh cli to get branch name"
                    echo branch=$(gh pr view $PR --repo $REPO --json headRefName --jq '.
                  headRefName') >> $GITHUB_OUTPUT
                  fi
              env:
                  HEAD_REF: ${{ github.event.pull_request.head.ref }}
                  PR: ${{ github.event.issue.number }}
                  REPO: ${{ github.repository }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - id: run-e2e
              name: Run tests
              uses: eventespresso/actions/packages/e2e-tests@CHORE/create-e2e-tests-package
              with:
                  cafe_repo_branch: DEV
                  barista_repo_branch: ${{ steps.get-branch.outputs.branch }}
                  e2e_tests_repo_branch: master
