name: E2E Runner

on:
    issue_comment:
        types: [created]
    pull_request_review:
        types: [submitted]

jobs:
    run-tests:
        name: Run E2E Tests
        runs-on: ubuntu-22.04
        if: |
            github.event.review.state == 'approved' ||
            contains(github.event.comment.body, '/run-e2e')
        timeout-minutes: 60
        steps:
            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v2
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

            - name: Run E2E Tests
              uses: eventespresso/actions/packages/e2e-tests@CHORE/create-e2e-tests-package
              with:
                  cafe_repo_branch: DEV
                  barista_repo_branch: master
                  e2e_tests_repo_branch: master
