name: E2E Runner

# Target submitted Pull Request Reviews
# See below job "Check" for more granular targetting
on: pull_request

jobs:
    check-target:
        name: Pull Request Was Approved
        runs-on: ubuntu-latest
        if: github.event.review.state == 'approved'
        steps:
            - run: echo 'This PR was approved'

    run-tests:
        name: Run E2E Tests
        needs: check-target
        runs-on: ubuntu-22.04
        timeout-minutes: 60
        steps:
            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v2
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

            - name: Run E2E Tests
              uses: eventespresso/actions/packages/e2e-tests@CHORE/create-e2e-tests-package
              with:
                  cafe_repo_branch: DEV
                  barista_repo_branch: master
                  e2e_tests_repo_branch: master
