name: E2E Runner

on:
    pull_request_review:
        types: [submitted]
    issue_comment:
        types: [created]
    workflow_dispatch:
        inputs:
            cafe_repo_branch:
                description: Which branch to use for Cafe repository? (default 'DEV')
                type: string
                required: false
            barista_repo_branch:
                description: Which branch to use for Barista repository? (defaults to workflow branch)
                type: string
                required: false
            e2e_tests_repo_branch:
                description: Which branch to use for E2E Tests repository? (default 'MAIN')
                type: string
                required: false

jobs:
    check:
        name: Check conditions
        runs-on: ubuntu-22.04
        if: |
            github.event.review.state == 'approved' ||
            contains(github.event.comment.body, '/run-e2e') ||
            github.event_name == 'workflow_dispatch'
        outputs:
            approvals: ${{ steps.approvals.outputs.count }}
        steps:
            - name: Get PR approvals count (event 'pull_request_review' only!)
              id: approvals
              if: github.event_name == 'pull_request_review'
              run: |
                  count="$(gh pr view "$PR" --repo "$REPO" --json latestReviews --jq '.latestReviews | map(select(.state == "APPROVED")) | length')"
                  echo "count=$count" >> "$GITHUB_OUTPUT"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO: ${{ github.event.pull_request.head.repo.name }}
                  PR: ${{ github.event.pull_request.number }}

    branch:
        name: Get branch ref
        runs-on: ubuntu-22.04
        outputs:
            ref: |-
                ${{ steps.pull_request_review.outputs.branch || steps.issue_comment.outputs.branch || steps.workflow_dispatch.outputs.branch }}
        steps:
            - name: "Event: 'pull_request_review' Activity: 'submitted' State: 'Approved'"
              id: pull_request_review
              if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
              run: echo branch="${{ github.event.pull_request.head.ref }}" >> "$GITHUB_OUTPUT"
            - name: "Event: 'issue_comment' Activity: 'created' Type: 'Pull Request' Comment Body: '/run-e2e' (contains)"
              id: issue_comment
              if: |
                  github.event_name == 'issue_comment' &&
                  github.event.issue.pull_request &&
                  contains(github.event.comment.body, '/run-e2e')
              run: |
                  branch="$(gh pr view "$PR" --repo "$REPO" --json headRefName --jq '.headRefName')"
                  echo branch="$branch" >> "$GITHUB_OUTPUT"
              env:
                  PR: ${{ github.event.issue.number }}
                  REPO: ${{ github.repository }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: "Event: 'workflow_dispatch' Activity: 'not applicable'"
              id: workflow_dispatch
              if: github.event_name == 'workflow_dispatch'
              run: echo branch="${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

    e2e:
        name: Run E2E tests
        runs-on: ubuntu-22.04
        timeout-minutes: 60
        needs: branch
        if: needs.branch.outputs.ref
        concurrency:
            group: ${{ github.workflow }}-${{ needs.branch.outputs.ref }}
            cancel-in-progress: ${{ github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch' }}
        steps:
            - name: Setup SSH for git
              uses: MrSquaare/ssh-setup-action@v2
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}
            - name: Check branch ref
              run: test "${{ needs.branch.outputs.ref }}"
            - name: Run tests
              uses: eventespresso/actions/packages/e2e-tests@main
              with:
                  cafe_repo_branch: ${{ inputs.cafe_repo_branch || 'DEV' }}
                  barista_repo_branch: ${{ inputs.barista_repo_branch || needs.branch.outputs.ref }}
                  e2e_tests_repo_branch: ${{ inputs.e2e_tests_repo_branch || 'MAIN' }}
                  gpg_password: ${{ secrets.E2E_GPG_PASSWORD }}
                  gpg_cipher: AES256
              env:
                  E2E_TEST_CARD_PAYPAL_COMMERCE: ${{ secrets.E2E_TEST_CARD_PAYPAL_COMMERCE }}
                  E2E_TEST_CREDS_PPC_SANDBOX_CONNECT: ${{ secrets.E2E_TEST_CREDS_PPC_SANDBOX_CONNECT }}
