name: E2E Runner

on:
    pull_request_review:
        types: [submitted]
    issue_comment:
        types: [created]
    workflow_dispatch:
        inputs:
            cafe_repo_branch:
                description: 'Cafe branch to use? (default: DEV)'
                type: string
                required: false
            e2e_repo_branch:
                description: 'E2E branch to use? (default: MAIN)'
                type: string
                required: false

jobs:
    run-tests:
        name: Run E2E Tests
        runs-on: ubuntu-22.04
        # two conditions which trigger E2E checks
        #   - PR is approved
        #   - PR contains comment "/run-e2e" (manual trigger)
        if: |
            github.event.review.state == 'approved' ||
            (
                github.event.issue.pull_request &&
                contains(github.event.comment.body, '/run-e2e')
            ) ||
            github.event_name == 'workflow_dispatch'
        # avoid excessively high timeout values to avoid burning minutes
        timeout-minutes: 60
        steps:
            - id: ssh
              name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v2
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}
            # In case of pull_request_review, we have access to HEAD REF of pull request. However, in case of issue_comment, we do not since event issue_comment always runs against default branch:
            # Note: This event will only trigger a workflow run if the workflow file is on the default branch.
            # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review
            # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
            - id: get-branch
              name: Get Branch Ref of the Pull Request
              run: |
                  if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
                      echo "Found branch name in \$GITHUB_REF_NAME: $GITHUB_REF_NAME"
                      echo "branch=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
                      exit 0
                  fi
                  # if condition earlier takes care of 'approved'-only PR submissions
                  if [ $GITHUB_EVENT_NAME" == "pull_request_review" ]; then
                      branch="$(gh pr view $GITHUB_PR --repo $GITHUB_REPO --json headRefName --jq '.headRefName')"
                      echo "Found branch using gh cli: $branch"
                      echo "branch=$branch" >> $GITHUB_OUTPUT
                      exit 0
                  fi
                  echo "Could not obtain branch name!"
                  exit 1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_REF: ${{ env.GITHUB_REF }}
                  GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
                  GITHUB_PR: ${{ github.event.issue.number }}
                  GITHUB_REPO: ${{ github.repository }}
            - id: run-e2e
              name: Run tests
              uses: eventespresso/actions/packages/e2e-tests@main
              with:
                  cafe_repo_branch: ${{ inputs.cafe_repo_branch || 'DEV' }}
                  barista_repo_branch: ${{ steps.get-branch.outputs.branch }}
                  e2e_tests_repo_branch: ${{ inputs.e2e_repo_branch || 'MAIN' }}
                  gpg_password: ${{ secrets.E2E_GPG_PASSWORD }}
                  gpg_cipher: AES256
              env:
                  E2E_TEST_CARD_PAYPAL_COMMERCE: ${{ secrets.E2E_TEST_CARD_PAYPAL_COMMERCE }}
                  E2E_TEST_CREDS_PPC_SANDBOX_CONNECT: ${{ secrets.E2E_TEST_CREDS_PPC_SANDBOX_CONNECT }}
