name: Pull Request checks

on: [pull_request]

env:
    PLAYWRIGHT_BROWSERS_PATH: 0 # See https://playwright.dev/docs/ci/#caching-browsers

    # Cancels (by default) all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    # Cancel only if the commit message does not contain "no-cancel"
    cancel-in-progress: ${{ !contains(github.event.commits[0].message, 'no-cancel') }}

jobs:
    # JOB to check if the files in a path have changed
    what-is-hit:
        runs-on: ubuntu-latest
        outputs:
            js: ${{ steps.filter.outputs.js }}
        steps:
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: ${{ github.ref }}
                  filters: |
                      js:
                        - 'domains/**'
                        - 'packages/**'
                        - 'yarn.lock'

    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                task: [lint, build, test]
        name: ${{ matrix.task }}
        needs: what-is-hit
        steps:
            - name: Checkout and yarn
              uses: eventespresso/actions/packages/checkout-and-yarn@main
              with:
                  # To make sure all history is fetched for jest --changedSince to work as expected
                  fetch-depth: ${{ ( matrix.task != 'test' && 1 ) || 0 }} # 0 for test, 1 otherwise

            - name: Set test CLI args
              # Run all unit tests if the commit message contains "test-all".
              if: ${{ matrix.task == 'test' && !contains(github.event.commits[0].message, 'test-all') }}
              run: echo "CLI_ARGS=--changedSince ${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

            - name: Run ${{ matrix.task }}
              # Run the task only if JS is affected
              if: ${{ needs.what-is-hit.outputs.js == 'true' }}
              run: yarn ${{ matrix.task }}:ci ${{ env.CLI_ARGS }}

            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              if: ${{ matrix.task == 'build' && needs.what-is-hit.outputs.js == 'true' }}
              with:
                  name: build
                  path: build/
