name: Pull Request checks

on: [pull_request]

env:
    PLAYWRIGHT_BROWSERS_PATH: 0 # See https://playwright.dev/docs/ci/#caching-browsers
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                task: [lint, build, test]
        name: ${{ matrix.task }}
        needs: what-is-hit
        steps:
            - name: Checkout the commit
              uses: actions/checkout@v2
              with:
                  # To make sure all history is fetched for jest --changedSince to work as expected
                  fetch-depth: ${{ ( matrix.task != 'test' && 1 ) || 0 }} # 0 for test, 1 otherwise
                  token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}

            # TODO replace this when setup-node action supports LTS alias
            - name: Set up Node
              uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              # install deps only if lockfile has changed
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            - name: Set test CLI args
              if: ${{ matrix.task == 'test' }}
              run: echo "CLI_ARGS=--changedSince ${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

            - name: Run ${{ matrix.task }}
              # Run the step only if it's not build or e2e is affected
              if: ${{ matrix.task != 'build' || needs.what-is-hit.outputs.e2e == 'true' }}
              run: yarn ${{ matrix.task }}:ci ${{ env.CLI_ARGS }}

            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              if: ${{ matrix.task == 'build' && needs.what-is-hit.outputs.e2e == 'true' }}
              with:
                  name: build
                  path: build/

    # JOB to check if the files in a path have changed
    what-is-hit:
        runs-on: ubuntu-latest
        outputs:
            e2e: ${{ steps.filter.outputs.e2e }}
        steps:
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: ${{ github.ref }}
                  filters: |
                      e2e:
                        - 'domains/**'
                        - 'packages/**'
                        - 'yarn.lock'

    e2e:
        name: E2E Tests
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node
              uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            - name: Download build artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: build/

            # Leave this here just in case "needs" field is removed, then it can be enabled
            # - name: Build barista assets
            #   run: yarn && yarn build

            - name: Install WordPress
              run: yarn wp-env start

            - name: Setup Playwright
              uses: microsoft/playwright-github-action@v1

            - name: Running the tests
              run: yarn test:e2e

            - name: Archive debug artifacts (screenshots, HTML snapshots)
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: playwright-artifacts
                  path: artifacts
