name: 'Ready for Review Notice'
on:
    pull_request:
        types: [ready_for_review, review_requested]

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    post-review-notice:
        runs-on: ubuntu-latest
        steps:
            - name: post review notice
              id: slack
              uses: slackapi/slack-github-action@v1.22.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID_DEV }}
                  payload: |
                      {
                        "text": "<!here> RFR :point_right: <https://github.com/eventespresso/barista/pull/${{ github.event.number
                        }}|${{ github.event.pull_request.title }} #${{ github.event.number }}>"
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_TOKEN }}
