name: 'Ready for Testing or Merge Notice'
on:
    pull_request:
        types: [labeled]

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    send-ready-for-testing-notice:
        if: "${{ github.event.label.name == 'S9: needs testing 🧪' }}"
        runs-on: ubuntu-latest
        steps:
            - name: send testing notice
              id: slack
              uses: slackapi/slack-github-action@v1.22.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID_SUPPORT_DESK }}
                  payload: |
                      {
                          "text": "<!here> Ready for Testing :test_tube: <https://github.com/eventespresso/barista/pull/${{ github.event.number}}|${{ github.event.pull_request.title }} #${{ github.event.number }}>"
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_TOKEN }}

    send-merge-notice:
        if: "${{ github.event.label.name == 'S:10 merge 🖇' }}"
        runs-on: ubuntu-latest
        steps:
            - name: send merge notice
              id: slack
              uses: slackapi/slack-github-action@v1.22.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID_DEV }}
                  payload: |
                      {
                          "text": "<!here> Ready to Merge :linked_paperclips: <https://github.com/eventespresso/barista/pull/${{ github.event.number}}|${{ github.event.pull_request.title }} #${{ github.event.number }}>"
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_TOKEN }}
